code: probability-distribution
title: Probability Distribution
toc:
  - code: about
    title: About
    id: 242317ad-dbaa-4b61-94a8-3395f6d807db
    topics:
      - code: book
        title: Book
        id: 8cbddebc-029a-4b86-9d7c-b89289aa0047
      - code: author
        title: Author
        id: 51fb4d3e-7327-4593-b2ab-cb33384ed4b5
  - code: perspectives-on-probability
    title: Perspectives on Probability
    id: de1f3d26-a624-4d83-9196-a4bd316c809b
    topics:
      - code: so-what-is-probability
        title: 'So, What is Probability?'
        id: 131ed7f0-ef19-4481-bc74-0c7ff851d1b9
